### ISSUE TITLE
Question on explicit property of registry on model

### ISSUE THREAD

**Issue by petreboy14** [AmpersandJS/ampersand-registry#3]
Hey just a couple of questions. 
1) Can a collection be given a registry property or only a model. 
2) What repo should I look in to find the code that auto populates a model in the registry when it's explicitly defined on the model definition? I've been hunting around and having trouble finding it.

**Comment by simme** [comment]
Would be really neat if the docs for the registry could be removed from the [npm page](https://www.npmjs.com/package/ampersand-registry). That would've saved me a lot of confusion! :P

**Comment by HenrikJoreteg** [comment]
@simme sorry, also, I don't quite follow what you're saying. You mean remove it from npm entirely?

**Comment by simme** [comment]
Sorry for being unclear. No, I mean the notion of a registry property on ampersand-model. The docs on github are not the same.

**Comment by HenrikJoreteg** [comment]
Oh, so we just need to publish a patch update it sounds like.

**Comment by HenrikJoreteg** [comment]
@simme, I think perhaps i'm dense. But I'm still not understanding what you're saying we should do.

**Comment by simme** [comment]
The [README at npm](https://www.npmjs.com/package/ampersand-registry) talks about the `registry` property on `ampersand-model`. Which — according to this thread — has been deprecated.

The [README on GitHub](https://github.com/ampersandjs/ampersand-registry) on the other hand shows you how to register a model with the registry inside the initialize method of a model and does not mention this property.

It also seems like the latest version published to npm is 0.2.2 while the latest version on GitHub is 0.2.3. So it seems like all you have to do is push the latest version to npm!

**Comment by HenrikJoreteg** [comment]
New release published to sync versions on npm and github, both now a `0.2.4`. Closing.
