### ISSUE TITLE
Question about forcing state objects to use the registry

### ISSUE THREAD

**Issue by adamyonk** [AmpersandJS/ampersand-registry#9]
I have models coming in from many different places in my app and I would like them to all be forced to use the registry. For example, if I `new SomeModel({ id: 1 })` and a model with ID 1 is already in the registry, I would like it to return that, instead of a new state object. Is it possible to highjack the state constructor and inject something like that?

**Comment by kamilogorek** [comment]
You can create simple wrapper to do that, something like

```js
function storeSomeModel (data) {
    return registry.lookup(data.modelType, data.id) || new SomeModel(data);
}
```

**Comment by gnimmelf** [comment]
Hi, sorry to drop in on this @kamilogorek, but could you expand on the above suggestion a bit?

-How and where would I hook into this? `model.fetch` and `model.save`?

@adamyonk you wouldn't happen to have an example of whatever solution you ended up with?

Cheers.

**Comment by HenrikJoreteg** [comment]
going to close this, feel free to re-open if unanswered.
